# __     __   ___    _____     ___       _
# \ \   / /  |_ _|  |__ __|   /   \     | |
#  \ \ / /    | |     | |    / ___ \    | |
#   \ V /     | |     | |   / _____ \   | |___
#    \_/     |___|    |_|  /_/     \_\  |______|

vital:
  # Whether the database is enabled (true/false)
  database-enabled: false

  # Prefix for messages
  prefix: "§l§4Vital  "

  # Default chat color
  chat-color: "GRAY"

  # Error message for no permission
  player-no-permission-error-message: "§l§cERROR! §r§cNo permissions!"

  # Error message for player not found
  player-not-found-error-message: "§l§cERROR! Player not found!"

  # Error message for non-player command execution
  command-only-player-error-message: "§l§cERROR! Command can only be executed by a Player!"

  # Error message for general command error
  command-error-message: "§l§cERROR! An error occurred while performing Command!"

  # Error message for invalid command arguments
  command-invalid-args-error-message: "§l§cERROR! Command does not support provided Arguments!"

  # Error message for internal command error
  command-internal-error-message: "§l§cERROR! Internal error while performing Command!"

  # User timeout value (in seconds)
  player-timeout: 0