package me.xra1ny.vital.logs;

import ch.qos.logback.classic.spi.ILoggingEvent;
import ch.qos.logback.core.AppenderBase;
import me.xra1ny.vital.VitalComponent;

/**
 * log handler to use when implementing custom operations when a log entry is generated by a SLF4J logger instance registered on vital's log context
 *
 * @author xRa1ny
 */
public abstract class VitalLogHandler extends AppenderBase<ILoggingEvent> implements VitalComponent {
    @Override
    public void onRegistered() {

    }

    @Override
    public void onUnregistered() {

    }
}
